### PR TITLE
Factor out Header class

### PR DESCRIPTION
**Pull request by sternj**

### CODE REVIEW

**Review by emeryberger — CHANGES_REQUESTED** [review]
Go ahead and remove the commented-out stuff from `libscalene.cpp`.

**Comment by sternj** [comment]
This was fixing an issue that did not exist

**Comment by sternj** [comment]
Reopening to rework for refactor

**Review by emeryberger — APPROVED** [review]
Minor comment - it's good practice to switch to using the more modern `#pragma once` in header files, which solves the problem that the `#ifndef` two-step handles.

**Pull request merged**
